### ISSUE TITLE
Image aspect ratio morphed/incorrect

### ISSUE THREAD

**Issue by tobire** [pascalw/kindle-dash#14]
First of all: excellent software!

I created a simple python script to create images to display. Unfortunately, the image is somehow morphed:
![IMG_20210216_220700](https://user-images.githubusercontent.com/1534148/108121620-6320b480-70a3-11eb-9755-948a82b27459.jpg)

This is the displayed file:
![db](https://user-images.githubusercontent.com/1534148/108121646-70d63a00-70a3-11eb-9d95-2299434e09b7.png)

I tried to load it directly from my python script aswell as directly from nginx and in both cases the image was morphed.

Would be nice if you have an idea on how to fix this :)

**Comment by pascalw** [comment]
Hi @tobire the Kindle only handles Grayscale PNGs correctly. Your PNG has an 8bit color/alpha profile. This is probably something you can specify in your Python code when generating the PNG. Alternatively you can convert the image using [pngcrush](https://pmt.sourceforge.io/pngcrush/): `pngcrush -c 0 dash.png`.

Let me know if that works!

**Comment by tobire** [comment]
It's kind of working now.
The image is not as stretched anymore but there are still not all 600x800 Pixels visible.
I added a border this time to make sure that I see it correctly:
![IMG_20210217_065735](https://user-images.githubusercontent.com/1534148/108162602-b9b2e080-70ed-11eb-8434-e9d470d98bc9.jpg)
![db](https://user-images.githubusercontent.com/1534148/108162609-bfa8c180-70ed-11eb-9bc2-12c5290167b5.png)

Are there any more requirements to the image in order for it to get displayed correctly?
Your example image is working fine btw.

**Comment by tobire** [comment]
Ah, nevermind, I made a mistake.
I used Pillow to convert the image to grayscale however the code found in a StackOverflow answer apparently did not work correctly.
After using pngcrush like you said, it's displayed correctly. 
Thanks for the help! :)

**Comment by tobire** [comment]
In case anyone else wants to convert their image to grayscale in Python, this code works:

`from PIL import Image, ImageOps
ImageOps.grayscale(Image.open('image.png')).save('grayscale.png')`

**Comment by pascalw** [comment]
Great! 👍
