### ISSUE TITLE
Render to png

### ISSUE THREAD

**Issue by kiru** [pascalw/kindle-dash#16]
Hello, 

You mention: 
> In my case I use a dashbling dashboard that I render into a PNG screenshot on a server.

What do you use to render the dashbling output to PNG? 

Thank you very much for this project!

Cheers, 
Kiru

**Comment by pascalw** [comment]
Hi Kiru! I'm using a headless Chrome browser using Puppeteer. I've put some information and a bit of code up [here](https://github.com/pascalw/kindle-dash/blob/main/docs/tipstricks.md).

**Comment by kiru** [comment]
Thank you, I missed that page initially. 
Ended up doing it with python (same principle as above) and convert the screenshot via ImageMagick

**Comment by pascalw** [comment]
Thanks for your feedback. Indeed it wasn't linked in the README. I've now added it to the README.
