### ISSUE TITLE
Move next_wakeup_secs to local

### ISSUE THREAD

**Issue by matopeto** [pascalw/kindle-dash#17]
Please move `next_wakeup_secs` method to `local` directory for user/kindles (like `fetch-dashboard.sh` that cannot use  `next-wakeup` binnary (eg. my kindle DXG). So users can implement own logick for next wakeup (e.g. hadcoded interval)

Maybe i will post PR for this issue later

**Comment by pascalw** [comment]
Hey thanks for the suggestion, that makes sense :-) If you can send a PR that would be great. If not I'll look into this myself later.

Btw for the Kindle DXG you could probably compile the `next-wakeup` binary for `armv5te`. Not 100% sure, but the CPU seems to be ARM5 compatible so it might work. But indeed if all you need is a hardcoded interval then it's overkill.

**Comment by matopeto** [comment]
@pascalw nice workaround without changing `dash.sh` :) and without compile custom binaries

My use case with my DXG is use it as the photo frame. DXG is without connectivity, so i similarly replace wait_for_wifi :) 

So i am closing this issue :) Thanks :)
