### ISSUE TITLE
Question: Battery life?

### ISSUE THREAD

**Issue by mrbrianhinton** [pascalw/kindle-dash#2]
I really appreciate this project. Thank you for sharing! If you have a second I'm really curious what the battery life has been doing this? Or have you kept it plugged in?

**Comment by matopeto** [comment]
Same question here :) I have "plugged on" weather dashboard (https://github.com/matopeto/kindle-weather-dashboard) and i wonder if this project can be replacement without cable

**Comment by pascalw** [comment]
I haven't yet run a full charge, but so far for me it consumes about 3-4% battery per day. I'm refreshing the screen every 30 minutes for 10 hours a day. The remaining hours the Kindle is suspended.

I expect the actual battery usage depends mostly on the number of screen refreshes per day. Refreshing an e-ink display is apparently quite power consuming.

**Comment by pascalw** [comment]
Closing this for now. Feel free to re-open if you have any other questions about battery life.

**Comment by matopeto** [comment]
FYI: Kindle DX, offline refresh (only pick random image from storage and show it), refresh every hour - battery life: 24 days

**Comment by pascalw** [comment]
Two more data points:

1. Kindle4NT refreshing every 30 minutes during office hours 5 days a week (about 100 screen refreshes per week), fetching an online image. Battery endures about 30 days.
2. Kindle4NT refreshing 4 times a day, 7 days a week (28 refreshes per week), fetching an online image. Battery also endures about 30 days.

I haven't looked at the remaining battery capacity of both devices, but I assume the second has a bit worse battery condition. In any case still happy charging only once per month :-)
