### ISSUE TITLE
Cron format has an unusual number of columns

### ISSUE THREAD

**Issue by coder543** [pascalw/kindle-dash#5]
The example cron schedule is `0 2,32 8-17 * * 2-6`, but... this has six columns, where a cron schedule is usually 5 columns.

Plugging this into [crontab.guru](https://crontab.guru/#0_2,32_8-17_*_*_2-6) results in a red mark and no text output.

I think the leading 0 is the issue here. If we erase that, then we get a [cron schedule](https://crontab.guru/#2,32_8-17_*_*_2-6) that sounds reasonable for a dashboard.

**Comment by pascalw** [comment]
Hey @coder543 the [cron library](https://crates.io/crates/cron) I'm using indeed uses a non-standard syntax. I'll make a note of it in the README, or perhaps I'll swap that library for [this one](https://crates.io/crates/cron-parser) which seems to be more standards compliant.

**Comment by coder543** [comment]
Ah, ok, that explains it. Thanks for the explanation!

**Comment by louis-ad** [comment]
I should've checked here before trying to figure out why my cron syntax kept failing, That cron library won't accept /10 for every 10 minutes, and it seems "0,15,30,45" is 1 item too many in a comma-separated list... quite dumb.

**Comment by pascalw** [comment]
I swapped out the cron library for another one that's more standards compliant. Now it takes expressions like `2,32 8-17 * * MON-FRI` (no more seconds) and `*/15 8-17 * * MON-FRI`. It's in the main branch and I'll make a new release probably later today or tomorrow.

**Comment by pascalw** [comment]
This is now released in https://github.com/pascalw/kindle-dash/releases/tag/v1.0.0-beta.3.
